### ISSUE TITLE
Crash upon more than character inserted into `Prefix` field

### ISSUE THREAD

**Issue by Succubyss** [MaggotHATE/Llama_chat#3]
I'm using `Llama_Chat_gguf_VK_vulkan_mini.exe` _(which I believe is what most NVIDIA GPU users should be using?)_ and on completely default settings, I'll go into "Text Settings" and type into this field:

![image](https://github.com/user-attachments/assets/127ecc64-a62b-4d16-a69a-842b53f1b24e)

But upon inserting more than 1 character, the program crashes.

P.S. Please make <kbd>Shift</kbd>+<kbd>Enter</kbd> always insert a newline irrespective of the toggle status of `Send messages by Enter` (should probably be changed to "_with_ Enter").

**Comment by MaggotHATE** [comment]
Hi! Thanks for the report, seems like Prefix is broken again, I'll look into it. Haven't used prefix for a long time.

As for `Shift`+`Enter`, I'm not sure it's possible in ImgUI (should be?), but it would be handy indeed.

**Comment by MaggotHATE** [comment]
Oh, and btw:
> *which I believe is what most NVIDIA GPU users should be using?*

Both Clblast and Vulkan versions are compatible with Nvidia GPUs, just be aware that Clblast doesn't work with MoE models.

**Comment by MaggotHATE** [comment]
> Pascal architecture if that makes a difference.

I see not much difference on my 1060 3GB (Vulkan is slightly faster, but each layer takes more VRAM), but that amount of VRAM is not enough to test that properly. However, Vulkan takes additional time to compile shaders on each launch, so it's a bit less convenient - and I don't use MoE models for now.

I've fixed the problem you've reported, please check. `Shift` + `Enter` should also work.
